public class ContentClass {

    /*
     # API Class
     -----------

   #1
    Class Nmae : AccountManager
    Usecase    : It is Standard API used for CRUD Operation on Account Object

    
   #2
    Class Nmae : APIGETRECORDUsingCountry
    Usecase    : It is Custom API to used for Finding Record using Country on Lead Object.

    #3
    Class Nmae : cAuthURIForApiREq
    Usecase    : It is used to Authorize Google Drive

    #3.1
    Class Nmae : cGoogleAppAuthenticationWithSalesforce
    Usecase    : It is used get Access Token from Google Drive


    #4
    Class Nmae : ContactsAccountNameChange
    Usecase    : This is Used to Select contact From Listview & then This is Contacts Account Name can be Changes at Once.
    AuraComp   : 	ContactAccountNameTransefer

     #5
    Class Nmae :
    Usecase    :

   #5
    Class Nmae :
    Usecase    :

   #5
    Class Nmae :
    Usecase    :

   #5
    Class Nmae :
    Usecase    :

   #5
    Class Nmae :
    Usecase    :

   #5
    Class Nmae :
    Usecase    :

   #5
    Class Nmae :
    Usecase    :

   #5
    Class Nmae :
    Usecase    :



     */
}